version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=batman-prod
    ports:
      - "8080:80"

    # env_file:
    #   - ./.env  (if we use .env file)